import { NextRequest, NextResponse } from "next/server";
import { getProjectByName, getProjectReleases, getProjectWithReadme } from "@/lib/queries";
import { getDependencyAuditSummary } from "@/lib/deps";
import { classifyLicense } from "@/lib/license";
import { cleanAuthor } from "@/lib/author-slug";
import { withRequestLog } from "@/lib/request-log";

/**
 * GET /api/projects/:name/md — Markdown rendering of a project, served as
 * text/markdown. Surfaced at /projects/:name.md via a rewrite in
 * next.config.ts. Designed for LLM retrieval (ChatGPT-User, PerplexityBot,
 * Claude-Web): clean prose, no JSX, stable URL, aggressive cache.
 */

const SITE = "https://www.freshcrate.ai";

function escapePipe(value: string | null | undefined): string {
  return (value || "").replace(/\|/g, "\\|").replace(/\n/g, " ").trim();
}

function md(name: string): string | null {
  const project = getProjectByName(name);
  if (!project) return null;

  const releases = getProjectReleases(project.id).slice(0, 10);
  const enriched = getProjectWithReadme(name);
  const audit = getDependencyAuditSummary(project.id);
  const license = classifyLicense(project.license);
  const author = cleanAuthor(project.author);
  const url = `${SITE}/projects/${encodeURIComponent(project.name)}`;

  const lines: string[] = [];
  lines.push(`# ${project.name}`);
  lines.push("");
  if (project.short_desc) {
    lines.push(`> ${project.short_desc}`);
    lines.push("");
  }
  lines.push(`- **URL**: ${url}`);
  lines.push(`- **Author**: ${author}`);
  lines.push(`- **Category**: ${project.category}`);
  lines.push(`- **Latest version**: \`${project.latest_version}\` (${new Date(project.release_date).toISOString().slice(0, 10)})`);
  lines.push(`- **License**: ${license.isNonStandard ? "non-standard" : license.display}`);
  if (project.repo_url) lines.push(`- **Source**: ${project.repo_url}`);
  if (project.homepage_url && project.homepage_url !== project.repo_url) {
    lines.push(`- **Homepage**: ${project.homepage_url}`);
  }
  if (enriched?.language) {
    lines.push(`- **Language**: ${enriched.language}`);
  }
  if (enriched && (enriched.stars > 0 || enriched.forks > 0)) {
    const parts: string[] = [];
    if (enriched.stars > 0) parts.push(`${enriched.stars.toLocaleString()} stars`);
    if (enriched.forks > 0) parts.push(`${enriched.forks.toLocaleString()} forks`);
    lines.push(`- **GitHub**: ${parts.join(", ")}`);
  }
  if (project.source_type) {
    lines.push(`- **Registry**: ${project.source_type}${project.source_package_id ? ` (\`${project.source_package_id}\`)` : ""}`);
  }
  if (project.tags.length > 0) {
    lines.push(`- **Tags**: ${project.tags.map((t) => `\`${t}\``).join(", ")}`);
  }
  lines.push("");

  if (project.description) {
    lines.push("## Description");
    lines.push("");
    lines.push(project.description.trim());
    lines.push("");
  }

  if (releases.length > 0) {
    lines.push("## Recent releases");
    lines.push("");
    lines.push("| Version | Date | Urgency | Changes |");
    lines.push("| --- | --- | --- | --- |");
    for (const r of releases) {
      const date = new Date(r.created_at).toISOString().slice(0, 10);
      lines.push(`| \`${escapePipe(r.version)}\` | ${date} | ${escapePipe(r.urgency)} | ${escapePipe(r.changes)} |`);
    }
    lines.push("");
  }

  if (audit) {
    lines.push("## Dependency audit");
    lines.push("");
    lines.push(`- **Score**: ${audit.score}/100`);
    lines.push(`- **Total deps**: ${audit.total_deps}`);
    lines.push(`- **Resolved**: ${audit.resolved}`);
    lines.push(`- **Unresolved**: ${audit.unresolved}`);
    lines.push(`- **License conflicts**: ${audit.conflict_count}`);
    lines.push(`- **Warnings**: ${audit.warning_count}`);
    if (audit.scanned_at) {
      lines.push(`- **Scanned**: ${new Date(audit.scanned_at).toISOString().slice(0, 10)}`);
    }
    lines.push("");
  }

  lines.push("## Citation");
  lines.push("");
  lines.push(`- HTML: ${url}`);
  lines.push(`- Markdown: ${url}.md`);
  lines.push(`- Dependencies JSON: ${SITE}/api/projects/${encodeURIComponent(project.name)}/deps`);
  lines.push("");
  lines.push(`_Generated by freshcrate.ai. Indexes ${project.source_type || "registry"} releases for AI-agent ecosystem packages._`);
  lines.push("");

  return lines.join("\n");
}

export const GET = withRequestLog(async (_request: NextRequest, ctx: { params: Promise<{ name: string }> }) => {
  const { name } = await ctx.params;
  const body = md(name);

  if (!body) {
    return new NextResponse(`# Not found\n\nNo project named \`${name}\` on freshcrate.ai.\n`, {
      status: 404,
      headers: { "Content-Type": "text/markdown; charset=utf-8" },
    });
  }

  return new NextResponse(body, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=86400, stale-while-revalidate=604800",
      "X-Robots-Tag": "index, follow",
    },
  });
});
